services:
  api:
    build: .
    container_name: device_monitor_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  flower:
    build: .
    command: celery -A app.celery_app flower
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
    env_file:
      - .env

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host=http://api:8000
    depends_on:
      - api

volumes:
  postgres_data:
